version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
  dj-cv-generator:
    container_name: backend-cv-generator
    build: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db


volumes:
  db:
